### PR TITLE
Some fixes and lost enhancements

### PR DESCRIPTION
**Pull request by Jako**
- Use template variables in title parameter
- Don't set where if title is a TV
- runSnippet should use element parameter

### CODE REVIEW

**Comment by Jako** [comment]
Added additional tvFilters with tv in title parameter option

In that case the addtional tvFilters have to be set with the AND/OR condition.

Example:
```
&title=`tvzip`
&tvFilters=`,country==Germany`
```

Normally the tvFilters parameter is only sended through SiteAtoZ.

**Comment by BobRay** [comment]
Jako, sorry for being so dense, but other than using $element with runSnippet(), I don't understand any of these changes well enough to explain them in the documentation, even after looking at the code.

I also don't understand why you need to prevent the &where property from taking effect.

**Comment by Jako** [comment]
https://github.com/Jako/SiteAtoZ/commit/d3811cfd287db6fe2e182c27a985022ec69c3d8d is necessary if the title is retrieved from a template variable. You can't filter the getResources/pdoResources call by where parameter in that case. You have to use the tvFilters parameter instead.

https://github.com/Jako/SiteAtoZ/commit/7569fe4630bf8457e6e790f45d8741beadcdc4ec is an addition to the code in the commit above (accidentally removed and recreated with https://github.com/Jako/SiteAtoZ/commit/9cd70e654ac7af1e4c0bf4a362de6faf24f2f975.

https://github.com/Jako/SiteAtoZ/commit/fda6060c563e3604565d5f27c1cb834158a6aa77 appends an additional tvFilters string to the getResources/pdoResources call. The example in the commit text is for the case that the title is retrieved from a template variable. It should also work if the title is a resource field, but then the AND condition in the example (,) has to be removed. https://github.com/Jako/SiteAtoZ/commit/550dddc601a3e0e9242197968dcbc7a72ece95bd is a small bugfix for tvFilters.

**Comment by BobRay** [comment]
Can you give me the use case for these? I can't think of a reason to use the content of a TV rather than the pagetitle as the title. Especially since you can easily edit the pagetitle. I must be missing something.

**Comment by Jako** [comment]
I am using it on a site to have addresses grouped by zip. Pagetitle is the name or company name there.

**Comment by BobRay** [comment]
I think I've got all your changes in V. 1.1.0-pl.  Let me know if anything is missing or doesn't work.

**Pull request closed without merging**
