### PR TITLE
Some output changes

### PR DESCRIPTION
**Pull request by Jako**

### CODE REVIEW

**Comment by BobRay** [comment]
Jako, thanks for all the work! ;)

If I merge all of these pull requests, will the snippet still work as it did before for current users without people changing anything?

**Comment by Jako** [comment]
The only thing that changes the output somehow happens in this commit. The div with class az-section is added in non JS output too and the items of each letter section are wrapped in a div with class az-items. Only classes were added and they do not change the behaviour of the snippet. The classes are necessary for grid support with boostrap-sass on http://seitter.partout.info/juweliere-und-haendler/. I have not checked it with the default css.

The other changes:
#3 adds a property that could disable css output (false by default)
#4 makes tvs in title parameter possible (getressources & pdoresources will be called with &tvfilters then)
#5 adds pdoResources support
#6 is a bugfix for an stray span that occurs with a not empty headingSeparator property
#7 removes not filled sections (az-header and az-noData) if they are not filled

**Comment by BobRay** [comment]
Jaok, thanks again. These PRs are giving me fits. I made some changes that hadn't yet been pushed to this repo, so. I can't do a fast-forward merge of any of them. I don't know why, because all I changed was the tutorial and you didn't mess with that.

Also, your patch-6 branch seems to have a merge conflict with the other ones. Perhaps you made the pull requests in a different order than you made the changes? I can implement the simple ones by hand. Maybe I should do that and we can go from there?

I've pushed my latest version to both my branches.

**Comment by BobRay** [comment]
PS: I've created a new branch called jako which is up-to-date. If you do any more PRs, please choose that as the target branch.

**Comment by Jako** [comment]
Instead of merging the commits you could cherry pick the commits by command line.

Look here for a fast start: https://swsblog.stanford.edu/blog/cherry-picking-small-git-lesson

**Pull request closed without merging**
